### ISSUE TITLE
Add SVG logo

### ISSUE THREAD

**Issue by JimiC** [SWI-Prolog/plweb-www#16]
Can we have the [logo](https://github.com/SWI-Prolog/plweb-www/blob/master/icons/swipl-120.png) in SVG? Would really like to include it on our [vscode-icons](https://github.com/vscode-icons/vscode-icons) collection.

Thanks in advance.

**Comment by JanWielemaker** [comment]
I'm afraid I do not have that.  I have a PDF version and can create .PNG at any resolution.  Never found a PDF to SVG tool that manages to convert the logo without it getting ugly due to slightly different placement and colouring of the parts that constitute the logo.

**Comment by JimiC** [comment]
@JanWielemaker Thanks for the fast reply. I guess our only solution is to wait for an art designer to volunteer and create the logo in SVG.

Thanks again.

**Comment by JanWielemaker** [comment]
I'll try to contact the designer.  Might not be easy as the original contact was rather indirect ...

**Comment by JimiC** [comment]
Any effort is highly appreciated.

**Comment by Anniepoo** [comment]
Jan - I seem to recall we tried to chase it down before, and discovered it was indeed made in photoshop, and hence didn't have a vector version available.

If I'm wrong, having a vector version would certainly be useful.

**Comment by JimiC** [comment]
If we could get our hands on the photoshop file then we might be able to extract it as an SVG (latest Adobe products give than ability).

**Comment by Anniepoo** [comment]
well, if you  just want it as rasteerized <image> element in SVG I can do that. How big?

**Comment by JimiC** [comment]
Well, rasterized won't do. The thing with latest Photoshop CC 2017 is that it can export the layers as vector paths, and we then can apply some Illustrator CC 2017 magic on them to match the coloring.

**Comment by Anniepoo** [comment]
Hmm.. and maybe I decided the original was photoshop after close inspection of the gradients made me realize they wouldn't be easy to match in illustrator. I tried to manually make a copy in illustrator without much luck.

**Comment by o314** [comment]
For what it's worth, i have a few days ago try to redesign the icon as svg by following the flat design pattern.

[logo-swi-prolog.pdf](https://github.com/SWI-Prolog/plweb-www/files/722444/logo-swi-prolog.pdf)

Some colors may be a bit dark. Contouring is relatively rough. I's a draft.

I put a pdf + zip of svg: [logo-swi-prolog.zip](https://github.com/SWI-Prolog/plweb-www/files/722445/logo-swi-prolog.zip) since github does not allow to upload svg.

I put it in the public domain. Please note, that is a derivated work and some rights can apply.

**Comment by JanWielemaker** [comment]
Enjoy at http://www.swi-prolog.org/icons/vector/swipl-logo.svg
Thanks to Steve Reeves (the designer).

**Comment by JimiC** [comment]
@JanWielemaker Can you check the link again?

**Comment by JanWielemaker** [comment]
If I click the link I get a familiar image :)  Possibly you were too early and the image had not yet arrived on one of the backend servers.  Can take a few hours before all is in sync again.

**Comment by JimiC** [comment]
Yeap. Now it's working. We really really appreciate all the effort. Many thanks to all for making this a reality. Much obliged.

**Comment by Anniepoo** [comment]
Hoot! Been wanting this a long time!

**Comment by Anniepoo** [comment]
So, when I see the image in chrome it's our familiar owl.  When I ctrl-U it it looks like svg,
When I import into illustrator I get pathws with all fill colors black, using the one inside the zip file, andan error if I 'save as' the image. one in zip file is 2K, d/ls are 400K, they're svg's with just rasters in them.
Any way we can get the ai file?

**Comment by JimiC** [comment]
@Anniepoo @o314 version is just the `png` wrapped as `svg`. The version @JanWielemaker provided is pure `svg`. The `xmpGImg:image` tags you see are the filters that get rasterized because unfortunately, the logo doesn't use pure `svg filters`.

**Comment by Anniepoo** [comment]
turns out I've got a pdf that seems to come into illustrator as vectors.

**Comment by Anniepoo** [comment]
[swipl-logo-as-vector.zip](https://github.com/SWI-Prolog/plweb-www/files/781215/swipl-logo-as-vector.zip)

**Comment by Anniepoo** [comment]
that's a zip with an ai file in it.

**Comment by JimiC** [comment]
The file seems fine to me.

**Comment by JimiC** [comment]
@Anniepoo What version of Illustrator do you have?

**Comment by Anniepoo** [comment]
AI CS5

**Comment by JimiC** [comment]
Here you go. Official logo in CS5 [swipl-logo.zip](https://github.com/SWI-Prolog/plweb-www/files/781479/swipl-logo.zip)

**Comment by sbrl** [comment]
I'm hosting an svg version of the `ai` file above (without the text) here: https://starbeamrainbowlabs.com/images/logos/swi-prolog.svg

**Comment by JanWielemaker** [comment]
Looks nice!
