### ISSUE TITLE
Dead link in prologlamp / cliopatria

### ISSUE THREAD

**Issue by o314** [SWI-Prolog/plweb-www#17]
In file https://github.com/SWI-Prolog/plweb-www/blob/master/FAQ/PrologLAMP.txt

the link http://cliopatria.swi-prolog.org/help/source/doc/home/vnc/prolog/src/ClioPatria/web/help/whitepaper.txt is dead

**Comment by JanWielemaker** [comment]
Thanks.  Fixed (on wiki; will reach github at some point)
