### ISSUE TITLE
Version Number of latest/current/dev release

### ISSUE THREAD

**Issue by quakerquickoats** [SWI-Prolog/plweb-www#22]
So I had a local copy of SWI-Prolog, wondering what the latest version available was, and scoured and scavenged the website. Could not find it anywhere! Is the version number hiding somewhere, or could we have a little news bit somewhere showing releases, like many of us could be accustomed to with our favorite implementations of our favorite languages? Thanks ^_^

**Comment by JanWielemaker** [comment]
What is wrong with http://www.swi-prolog.org/Download.html

**Comment by quakerquickoats** [comment]
Thanks for your response.
