### ISSUE TITLE
"CQL" link is broken in "Using SWI-Prolog for commercial applications"

### ISSUE THREAD

**Issue by dram** [SWI-Prolog/plweb-www#23]
Page "Using SWI-Prolog for commercial applications" (http://www.swi-prolog.org/commercial/index.html) linked to "CQL" with URL http://www.swi-prolog.org/pldoc/doc/swi/library/cql/cql.pl, which is broken.

**Comment by JanWielemaker** [comment]
Thanks.  Fixed (may take a few hours to be visible everywhere)
