### ISSUE TITLE
Please update FAQ about toplevel_print_options

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/plweb-www#6]
[Issue #139](https://github.com/SWI-Prolog/swipl-devel/issues/139) arose due to `toplevel_print_options`'s being mentioned in the FAQ.

Please update the entry about [**All Output**](http://eu.swi-prolog.org/FAQ/AllOutput.html) to whatever should now be used. Thank you!

**Comment by JanWielemaker** [comment]
Updated
