### ISSUE TITLE
Many links in the FAQ overview are not correctly formatted

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/plweb-www#7]
At least 8 of the links are not displayed as intended:

[http://eu.swi-prolog.org/FAQ/](http://www.swi-prolog.org/FAQ/)

For example, instead of:

```
[[Prolog writes [x, y, z|...], I want the whole answer][AllOutput]]
```

I expect to see:

[**Prolog writes [x, y, z|...], I want the whole answer**](http://eu.swi-prolog.org/FAQ/AllOutput.html)

**Comment by JanWielemaker** [comment]
Was caused by the token limit for labels in PlDoc.  Raised.
